# Generated by Django 5.1.2 on 2024-11-05 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appGP', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proyecto',
            old_name='fecha_inicio',
            new_name='fecha_creacion',
        ),
        migrations.RenameField(
            model_name='proyecto',
            old_name='fecha_fin',
            new_name='fecha_entrega',
        ),
        migrations.RemoveField(
            model_name='tarea',
            name='usuario',
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('dni', models.TextField(max_length=8)),
                ('telefono', models.CharField(blank=True, max_length=9)),
                ('edad', models.PositiveIntegerField()),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personas', to='appGP.tarea')),
            ],
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
