# Generated by Django 5.1.3 on 2024-11-14 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appGP', '0003_alter_tarea_fecha_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='ImagenPersona',
            field=models.URLField(blank=True, max_length=600, null=True),
        ),
    ]
