# Generated by Django 5.1.2 on 2024-11-22 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appGP', '0004_persona_imagenpersona'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='correo_electronico',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='direccion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='rol',
            field=models.CharField(choices=[('Manager', 'Manager'), ('Developer', 'Desarrollador'), ('Tester', 'Tester')], default='Developer', max_length=50),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='estado',
            field=models.CharField(choices=[('active', 'Activo'), ('completed', 'Completado'), ('paused', 'En pausa')], default='active', max_length=50),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='presupuesto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='tarea',
            name='prioridad',
            field=models.CharField(choices=[('Urgent', 'Urgente'), ('Normal', 'Normal'), ('Optional', 'Opcional')], default='Normal', max_length=20),
        ),
        migrations.AddField(
            model_name='tarea',
            name='tiempo_estimado',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
