# Generated by Django 5.1.2 on 2024-12-08 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appGP', '0005_persona_correo_electronico_persona_direccion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='presupuesto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True),
        ),
    ]
