# Generated by Django 5.1.2 on 2024-12-08 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appGP', '0007_alter_persona_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='rol',
            field=models.CharField(choices=[('Manager', 'Manager'), ('Developer', 'Desarrollador'), ('Tester', 'Tester'), ('FootballPlayer', 'Futbolista'), ('ArmedForces', 'Fuerzas Armadas'), ('Student', 'Estudiante')], default='Developer', max_length=50),
        ),
    ]
